-- 프롬피 시드 데이터 (자동 생성: scripts/generate-seed.mjs)
-- schema.sql 을 먼저 실행한 뒤, 이 파일을 SQL Editor 에 붙여넣고 RUN 하세요.

insert into public.prompts
  (title, body, description, category, model, image_url, aspect, tags, author_name, author_avatar, likes, saves)
values
  ($$네온 사이버펑크 도시 야경$$, $$a sprawling cyberpunk city at night, neon signs reflecting on wet streets, flying cars, cinematic lighting, ultra detailed, 8k --ar 2:3 --style raw$$, $$비 내린 밤거리의 네온 사이버펑크 도시를 그릴 때 쓰는 프롬프트예요. 끝의 --ar 2:3 은 세로 비율, --style raw 는 사실적인 질감을 줍니다. 'neon signs', 'flying cars' 부분을 원하는 요소로 바꿔보세요.$$, $$디자인/이미지$$, $$Midjourney$$, $$https://picsum.photos/seed/cyber/600/900$$, $$portrait$$, array[$$사이버펑크$$, $$도시$$, $$야경$$]::text[], $$민지$$, $$https://picsum.photos/seed/av1/80/80$$, 1243, 892),
  ($$수채화 느낌의 고양이 일러스트$$, $$cute cat sitting by the window, soft watercolor illustration, pastel colors, gentle morning light, children's book style$$, $$동화책 삽화 같은 부드러운 수채화 일러스트를 만드는 프롬프트입니다. 'cat'을 다른 동물로 바꾸면 같은 화풍으로 시리즈를 만들 수 있어요. 'pastel colors'를 빼면 색감이 더 진해집니다.$$, $$디자인/이미지$$, $$DALL·E 3$$, $$https://picsum.photos/seed/cat/600/600$$, $$square$$, array[$$수채화$$, $$고양이$$, $$일러스트$$]::text[], $$해든$$, $$https://picsum.photos/seed/av2/80/80$$, 980, 540),
  ($$미니멀 제품 촬영 스튜디오컷$$, $$minimalist product photography of a perfume bottle, soft studio lighting, beige background, subtle shadows, commercial look, high resolution$$, $$쇼핑몰 상세페이지나 광고에 쓸 깔끔한 제품 컷을 만드는 프롬프트예요. 'perfume bottle'을 판매하는 제품명으로 바꾸고, 'beige background'로 배경색을 조정하세요.$$, $$업무/생산성$$, $$Midjourney$$, $$https://picsum.photos/seed/product/600/750$$, $$portrait$$, array[$$제품사진$$, $$미니멀$$, $$스튜디오$$]::text[], $$서윤$$, $$https://picsum.photos/seed/av3/80/80$$, 756, 611),
  ($$판타지 숲속 요정 마을$$, $$a hidden fairy village inside a giant mushroom forest, glowing lanterns, magical atmosphere, dreamy fog, detailed fantasy art$$, $$게임 배경이나 동화 삽화로 좋은 환상적인 요정 마을 프롬프트입니다. 'glowing lanterns', 'dreamy fog' 같은 분위기 단어가 몽환적인 느낌을 좌우해요.$$, $$재미/캐릭터$$, $$Stable Diffusion$$, $$https://picsum.photos/seed/fairy/600/800$$, $$portrait$$, array[$$판타지$$, $$숲$$, $$요정$$]::text[], $$도윤$$, $$https://picsum.photos/seed/av4/80/80$$, 1520, 1102),
  ($$레트로 80년대 신스웨이브 포스터$$, $$retro 1980s sports car, synthwave sunset, grid horizon, bold magenta and cyan, vintage poster aesthetic$$, $$80년대 복고풍 신스웨이브 포스터를 만드는 프롬프트예요. 'sports car'를 다른 소재로 바꿔도 같은 레트로 색감(마젠타+시안)이 유지됩니다.$$, $$디자인/이미지$$, $$Midjourney$$, $$https://picsum.photos/seed/retro/600/600$$, $$square$$, array[$$레트로$$, $$자동차$$, $$신스웨이브$$]::text[], $$지호$$, $$https://picsum.photos/seed/av5/80/80$$, 643, 388),
  ($$따뜻한 북유럽 거실 인테리어$$, $$cozy scandinavian living room, warm wooden tones, large windows, plants, soft natural light, interior design magazine photo$$, $$인테리어 참고 이미지나 무드보드용으로 좋은 북유럽풍 거실 프롬프트입니다. 'living room'을 'bedroom', 'kitchen' 등으로 바꿔 공간별로 뽑아보세요.$$, $$취미/일상$$, $$DALL·E 3$$, $$https://picsum.photos/seed/interior/600/900$$, $$portrait$$, array[$$인테리어$$, $$북유럽$$, $$거실$$]::text[], $$하린$$, $$https://picsum.photos/seed/av6/80/80$$, 834, 702),
  ($$우주를 떠다니는 고래$$, $$a giant whale floating through space among nebulae and stars, surreal, ethereal, cosmic colors, highly detailed digital painting$$, $$초현실적인 분위기의 디지털 페인팅 프롬프트예요. 'whale'을 다른 동물로 바꾸면 우주를 떠다니는 시리즈를 만들 수 있습니다.$$, $$재미/캐릭터$$, $$Stable Diffusion$$, $$https://picsum.photos/seed/whale/600/700$$, $$landscape$$, array[$$우주$$, $$초현실$$, $$고래$$]::text[], $$유나$$, $$https://picsum.photos/seed/av7/80/80$$, 2104, 1699),
  ($$감성적인 브런치 음식 사진$$, $$gourmet brunch plate, avocado toast and poached egg, overhead shot, natural light, food blog style, appetizing and fresh$$, $$음식 블로그나 메뉴판에 쓸 먹음직스러운 사진을 만드는 프롬프트입니다. 'overhead shot'(위에서 찍기)을 'close-up'으로 바꾸면 클로즈업 컷이 나와요.$$, $$취미/일상$$, $$Midjourney$$, $$https://picsum.photos/seed/food/600/750$$, $$portrait$$, array[$$음식$$, $$플레이팅$$, $$브런치$$]::text[], $$건우$$, $$https://picsum.photos/seed/av8/80/80$$, 567, 421),
  ($$픽셀 아트 게임 배경$$, $$16-bit pixel art forest level, parallax background, warm sunset palette, retro game aesthetic, crisp pixels$$, $$레트로 게임 느낌의 픽셀아트 배경 프롬프트예요. 'forest level'을 'cave', 'city' 등으로 바꿔 스테이지별 배경을 만들 수 있습니다.$$, $$재미/캐릭터$$, $$Stable Diffusion$$, $$https://picsum.photos/seed/pixel/600/500$$, $$landscape$$, array[$$픽셀아트$$, $$게임$$, $$배경$$]::text[], $$시우$$, $$https://picsum.photos/seed/av9/80/80$$, 712, 503),
  ($$몽환적인 수중 세계$$, $$underwater dreamscape, bioluminescent jellyfish, deep blue gradients, rays of light piercing water, serene and magical$$, $$빛나는 해파리가 떠다니는 몽환적인 수중 이미지 프롬프트입니다. 'bioluminescent jellyfish'(빛나는 해파리)가 분위기의 핵심이에요.$$, $$디자인/이미지$$, $$Midjourney$$, $$https://picsum.photos/seed/ocean/600/850$$, $$portrait$$, array[$$수중$$, $$몽환$$, $$해파리$$]::text[], $$채원$$, $$https://picsum.photos/seed/av10/80/80$$, 1340, 988),
  ($$빈티지 카페 간판 로고$$, $$vintage coffee shop logo, hand-drawn lettering, warm brown and cream, rustic emblem style, badge design$$, $$가게 로고나 브랜드 엠블럼을 만들 때 쓰는 프롬프트예요. 'coffee shop'을 업종으로 바꾸고, 색상 단어(warm brown and cream)를 브랜드 색으로 교체하세요.$$, $$업무/생산성$$, $$DALL·E 3$$, $$https://picsum.photos/seed/logo/600/600$$, $$square$$, array[$$로고$$, $$빈티지$$, $$카페$$]::text[], $$예진$$, $$https://picsum.photos/seed/av11/80/80$$, 445, 356),
  ($$눈 내리는 일본 온천 마을$$, $$snowy japanese onsen town at dusk, steam rising, warm lantern glow, traditional wooden buildings, peaceful winter scene$$, $$여행 무드보드나 배경화면으로 좋은 겨울 온천 마을 프롬프트입니다. 'at dusk'(해질녘)를 'at night', 'in the morning'으로 바꿔 시간대를 조정하세요.$$, $$취미/일상$$, $$Midjourney$$, $$https://picsum.photos/seed/onsen/600/800$$, $$portrait$$, array[$$겨울$$, $$일본$$, $$온천$$]::text[], $$준서$$, $$https://picsum.photos/seed/av12/80/80$$, 1876, 1433);
